import os

SERVER_ADDRESS = os.environ["SERVER_ADDRESS"]
OIDC_SERVER_URL = os.environ["OIDC_SERVER_URL"]
OIDC_CLIENT_ID = os.environ["OIDC_CLIENT_ID"]
OIDC_CLIENT_SECRET = os.environ["OIDC_CLIENT_SECRET"]
SESSION_SECRET_KEY = os.environ["SESSION_SECRET_KEY"]
SESSION_REDIS_HOST = os.environ["SESSION_REDIS_HOST"]
SESSION_REDIS_PORT = os.environ["SESSION_REDIS_PORT"]
